/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package foursum;

import org.junit.Test;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertArrayEquals;;

public class FourSumTest {
    @Test
    public void testCubic() {
        // Should return null
        assertNull(FourSum.fourSumCubic(
            new int[] { 1, 2, 3, 4 }
        ));
        assertNull(FourSum.fourSumCubic(
            new int[] { 1, 2, 3, 4, 5, 6, 7 }
        ));

        // Should not return null
        assertNotNull(FourSum.fourSumCubic(new int[] { 1, 2, 3, -6 }));
        assertNotNull(FourSum.fourSumCubic(new int[] { 1, 2, 3, -3, -2 }));

        // Should return: new int[] { 1, 2, 3, -6 }
        assertArrayEquals(new int[] { 1, 2, 3, -6 },
            FourSum.fourSumCubic(new int[] { 1, 2, 3, -6 }
        ));
        // Should return: new int[] { 10, 30, 40, -80 } 
        assertArrayEquals(new int[] { 10, 30, 40, -80 },
            FourSum.fourSumCubic(new int[] { 10, 20, 30, 40, -80 }
        ));
    }

    @Test
    public void testQuartic() {
        // Should return null
        assertNull(FourSum.fourSumQuartic(
            new int[] { 1, 2, 3, 4 }
        ));
        assertNull(FourSum.fourSumQuartic(
            new int[] { 1, 2, 3, 4, 5, 6, 7 }
        ));

        // Should not return null
        assertNotNull(FourSum.fourSumQuartic(new int[] { 1, 2, 3, -6 }));
        assertNotNull(FourSum.fourSumQuartic(new int[] { 1, 2, 3, -3, -2 }));

        // Should return: new int[] { -6, 1, 2, 3 }
        assertArrayEquals(new int[] { -6, 1, 2, 3 },
            FourSum.fourSumQuartic(new int[] { 1, 2, 3, -6 }
        ));

        // Should return: new int[] { -14, 1, 3, 10 }
        assertArrayEquals(new int[] { -14, 1, 3, 10 },
            FourSum.fourSumQuartic(new int[] { -14, 1, 3, 10 }
        ));
    }

    @Test
    public void testHashMap() {
        // Should return null
        assertNull(FourSum.fourSumHashMap(
            new int[] { 1, 2, 3, 4 }
        ));

        assertNull(FourSum.fourSumHashMap(
            new int[] { 1, 2, 3, 4, 5, 6, 7 }
        ));

        // Should not return null
        assertNotNull(FourSum.fourSumHashMap(new int[] { 1, 2, 3, -6 }));
        assertNotNull(FourSum.fourSumHashMap(new int[] { 1, 2, 3, -3, -2 }));

        // Should return: new int[] { 1, 4, 5, -10 }
        assertArrayEquals(new int[] { 1, 4, 5, -10 },
            FourSum.fourSumHashMap(new int[] { 1, 2, 3, 4, 5, -10 }
        ));

        // Should return: new int[] { 1, 2, 3, -6 }
        assertArrayEquals(new int[] { 1, 2, 3, -6 },
            FourSum.fourSumHashMap(new int[] { 1, 2, 3, 4, -6 }
        ));
    }
}