/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package threesum;

import org.junit.Test;
import static org.junit.Assert.*;

public class ThreeSumTest {
    @Test public void appHasAGreeting() {
        ThreeSum classUnderTest = new ThreeSum();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
