/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment3;

import org.junit.Test;
import static org.junit.Assert.*;

public class BacktrackingSudokuTest {
    @Test
    public void testBacktrackingSudokuSolver() {
        // Should return true
        assertTrue("Should return true", BacktrackingSudokuSolver.backtrackingSudokuSolver(new int[][] { 
            { 0, 1, 0, 0 },
            { 2, 3, 1, 0 },
            { 0, 0, 3, 0 },
            { 0, 0, 0, 0 } }, 1, 1, 2));
        assertTrue("Should return true", BacktrackingSudokuSolver.backtrackingSudokuSolver(new int[][] { 
            { 1, 0, 0, 0 },
            { 0, 2, 0, 0 },
            { 0, 0, 3, 0 },
            { 0, 0, 0, 4 } }, 1, 1, 2));
        assertTrue("Should return true", BacktrackingSudokuSolver.backtrackingSudokuSolver(new int[][] { 
            { 1, 2, 3, 0, 0, 0, 0, 0, 0 },
            { 4, 5, 6, 0, 0, 0, 0, 0, 0 },
            { 7, 8, 9, 0, 0, 0, 0, 0, 0 },
            { 0, 0, 0, 1, 2, 3, 0, 0, 0 },
            { 0, 0, 0, 4, 5, 6, 0, 0, 0 },
            { 0, 0, 0, 7, 8, 9, 0, 0, 0 },
            { 0, 0, 0, 0, 0, 0, 1, 2, 3 },
            { 0, 0, 0, 0, 0, 0, 4, 5, 6 },
            { 0, 0, 0, 0, 0, 0, 7, 8, 9 } }, 1, 1, 3));

        assertFalse("Should return false", BacktrackingSudokuSolver.backtrackingSudokuSolver(new int[][] { 
            { 4, 1, 2, 3 },
            { 2, 3, 1, 4 },
            { 1, 2, 3, 0 },
            { 0, 0, 0, 0 } }, 1, 1, 2));
       
    }
}
