/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// To run: Navigate to foursum folder and run 'java -jar app/build/libs/app.jar (cubic, quadratic, hashmap)'

package foursum;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;

public class FourSum {
    public static int[] readData() {
        Scanner s = new Scanner(System.in);
        int[] x = null;
        try {
            int n = s.nextInt();
            x = new int[n];
            for (int i = 0; i < n; ++i) {
                x[i] = s.nextInt();
            }
        } finally {
            s.close();
        }
        return x;
    }

    // Cubic solution
    public static int[] fourSumCubic(int[] x) {
        int n = x.length;
        for (int i = 0; i < n; ++i) {
            int a = x[i];
            for (int j = i + 1; j < n; ++j) {
                int b = x[j];
                for (int k = j + 1; k < n; ++k) {
                    int c = x[k];
                    for (int l = k + 1; l < n; ++l) {
                        int d = x[l];
                        if (a + b + c + d == 0) {
                            return new int[] { a, b, c, d };
                        }
                    }   
                }
            }
        }
        return null;
    }

    // Quartic solution
    public static int[] fourSumQuartic(int[] x) {
        int n = x.length;
        int[] y = x.clone();
        Arrays.sort(y);
        for (int i = 0; i < n; ++i) {
            int a = y[i];
            for (int j = i + 1; j < n; ++j) {
                int b = y[j];
                int left = j + 1;
                int right = n - 1;
                while (left < right) {
                    int c = y[left];
                    int d = y[right];
                    if (a + b + c + d == 0) {
                        return new int[] { a, b, c, d };
                    } else if (a + b + c + d < 0) {
                        ++left;
                    } else {
                        --right;
                    }
                }
            }
        }
        return null;
    }

    // Hashmap solution
    public static int[] fourSumHashMap(int[] x) {
        int n = x.length;
        HashMap<Integer, int[]> H = new HashMap<Integer, int[]>();
        for (int i = 0; i < n; ++i) {
            for (int j = i+1; j < n; ++j) {
                H.put(x[i] + x[j], new int[] {i,j});
            }
        }

        for (int i = 0; i < n; ++i) {
            int a = x[i];
            for (int j = i + 1; j < n; ++j) {
                int b = x[j];
                int[] kl = H.get(-a - b);
                if (kl != null && j < kl[0]) {
                    int c = x[kl[0]];
                    int d = x[kl[1]];
                    return new int[] { a, b, c, d };
                }
            }
        }
        return null;
    }

    public static void main(String[] args) {
        int[] x = readData();
        int[] y = null;

        if ("cubic".equals(args[0])) {
            y = fourSumCubic(x);
        } else if ("quartic".equals(args[0])) {
            y = fourSumQuartic(x);
        } else if ("hashmap".equals(args[0])) {
            y = fourSumHashMap(x);
        }

        if (y == null) {
            System.out.println("null");
        } else {
            System.out.println(String.format("%d %d %d %d",
                 y[0], y[1], y[2], y[3]));
        }
    }
}
